twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # the value is the service's id
        categoryRepository: '@App\Repository\CategoryRepository'
        postRepository: '@App\Repository\PostRepository'

when@test:
    twig:
        strict_variables: true
